var quotesContainer = {
    "quotes": [
        { quote: '“Os problemas são oportunidades para se mostrar o que sabe.” (Duke Ellington)' },
        { quote: '“Nossos fracassos, às vezes, são mais frutíferos do que os êxitos.” (Henry Ford)' },
        { quote: '“Tente de novo. Fracasse de novo. Mas fracasse melhor”. (Samuel Beckett)' },
        { quote: '“É costume de um tolo, quando erra, queixar-se dos outros. É costume de um sábio queixar-se de si mesmo”. (Sócrates)' },
        { quote: '“O verdadeiro heroísmo consiste em persistir por mais um momento, quando tudo parece perdido”. (W. F. Grenfel)' },
        { quote: '“Cada cliente é como se fosse primeiro e único”. (Norman Bawes)' },
        { quote: '“Mesmo que já tenhas feito uma longa caminhada, há sempre um novo caminho a fazer”. (Santo Agostinho)' },
        { quote: '“Vender é construir uma ponte entre você e seu cliente e fazê-lo atravessar para o seu lado”. (Ciclo dos Profissionais de Venda)' },
        { quote: '“Na prosperidade, nossos amigos nos conhecem; na adversidade, nós é que conhecemos nossos amigos”. (Churton Collins)' },
        { quote: '“A felicidade não está em fazer o que a gente quer, e sim querer o que a gente faz”. (Jean Paul Sartre)' },
        { quote: '“Nada acontece a menos que sonhemos antes”. (Carl Sandburg)' },
        { quote: '“É sempre divertido fazer o impossível”. (Walt Disney)' },
        { quote: '“A coisa mais cara é transformar um cliente insatisfeito em satisfeito”. (Jan Carlzon)' },
        { quote: '“Experiência é o nome que cada um dá a seus erros”. (Oscar Wilde)' },
        { quote: '“Lembre sempre que a sua vontade de triunfar é mais importante do que qualquer outra coisa”. (Abraham Lincoln)' },
        { quote: '“Prefiro os erros do entusiasmo à indiferença da sabedoria”. (Anatole France)' },
        { quote: 'Na realidade, vendas e serviços são inseparáveis”. (Carter Brow)' },
        { quote: '“A arte de ser ora audacioso, ora prudente, é a arte de vencer”. (Napoleão Bonaparte)' },
        { quote: '“Seja corajoso. Mesmo que você não seja, finja ser. Ninguém nota a diferença”. (H. Jackson Brown Jr.)' },
        { quote: '“Não somos responsáveis apenas pelo que fazemos, mas também pelo que deixamos de fazer”. (Moliere)' },
        { quote: '“A estratégia de marketing começa, termina, vive e morre com o cliente”. (Michael Gerber)' },
        { quote: '“Quando você contrata pessoas mais inteligentes do que você, prova que é mais inteligente do que elas”. (R. H. Grant)' },
        { quote: '“O talento vence jogos, mas só o trabalho em equipe vence campeonatos”. (Michael Jordan)' },
        { quote: '“Um negócio nunca é bom se com ele conseguimos um inimigo”. (Hugh Prather)' },
        { quote: '“Um objetivo nada mais é do que um sonho com limite de tempo”. (Joel L. Griffith)' },
        { quote: '“Sorte é o que acontece quando a preparação encontra a oportunidade”. (Elmer Letterman)' },
        { quote: '“O mercado dita inovações. Quem não segue vira peça de museu”. (Phill Knight)' },
        { quote: '“O único lugar que o sucesso vem antes do trabalho é no dicionário”. (Vidal Sasson)' },
        { quote: '“Se você quiser ir daqui para lá no mundo dos negócios, não encontrará nenhuma linha reta para levá-lo”. (William Ahmanson)' },
        { quote: '“Integridade é a essência de todo negócio”. (R. Buckminster Fuller)' },
        { quote: '“Existe o risco que você jamais pode correr. Existe o risco que você jamais pode deixar de correr”. (Peter Drucker)' },
        { quote: '“As duas coisas mais importantes não aparecem no balanço da empresa: sua reputação e o seu time”. (Henry Ford, adaptação)' },
        { quote: '“A qualidade do seu trabalho tem tudo a ver com a qualidade da sua vida”. (Orison Swett Marden)' },
        { quote: '“Nenhuma empresa pode ter sucesso tentando tudo para todos”. (Michael Treacy)' },
        { quote: '“Nunca se esqueça de um cliente; e nunca deixe que um cliente esqueça você”. (Walter Reuther)' },
        { quote: '“Somos o que repetidamente fazemos. Portanto, a excelência não é um feito, é um hábito”. (Aristóteles)' },
        { quote: '“Persistência é irmã gêmea da excelência. Uma é mãe da qualidade, a outra a mãe do tempo”. (Marabel Morgan)' },
        { quote: '“O propósito de uma companhia é criar e manter o cliente”. (Theodoro Levitt)' },
        { quote: '“Comemore os seus sucessos. Veja com humor os seus fracassos”. (Sam Walton)' },
        { quote: '“Autorrespeito, autoconhecimento e autocontrole conduzem a vida ao poder supremo”. (Alfred Tennyson)' },
        { quote: '“É tentando o impossível que se chega à realização do possível”. (Henri Barbusse)' },
        { quote: '“Ganharão o jogo empresas que têm como missão exceder as expectativas dos clientes”. (Richard Whiteley)' },
        { quote: '“Toda empresa precisa ter gente que erra, que não tem medo de errar e que aprende com erro”. (Bill Gates)' },
        { quote: '“A confiança em si mesmo é o primeiro segredo do sucesso”. (Ralph Waldo Emerson)' },
        { quote: '“Aquele que pretende ser um líder tem que ser uma ponte”. (Provérbio Galês)' },
        { quote: '“Sempre que se vê um empreendimento de sucesso é porque alguém antes tomou uma decisão destemida”. (Peter Ducker)' },
        { quote: '“Serviços aos clientes é uma estratégia de marketing”. (John Tschohl)' },
        { quote: '“Muda tuas ideias e mudarás teu mundo”. (Norman Vincent Peale)' },
        { quote: '“Sua tarefa como líder é criar uma atmosfera que transforme o antagonismo em energia criativa”. (John Kao)' },
        { quote: '“A publicidade traz os clientes até a porta; mas o mau serviço envia eles direto para fora”. (John Tschohl)' },
        { quote: '“Único cliente bom é o cliente feliz. Lembre-se: clientes felizes adoram gastar dinheiro”. (Daryl Bernstein)' },
        { quote: '“Devemos prometer somente aquilo que podemos entregar e entregar mais do que prometemos”. (Jean Rozwadowski)' },
        { quote: '“Nada de importante no mundo foi realizado sem paixão”. (Georg Wilhelm)' },
        { quote: '“Quem tem a obrigação de visualizar o futuro não é o cliente”. (Célia Chaim)' },
        { quote: '“Profissional nota 10 é aquele que tem 2 pontos de esforço, 3 pontos de talento e 5 pontos de caráter”. (Roland Barthes)' },
        { quote: '“Uma das melhores maneiras de convencer os outros é ouvindo. Ouça todos”. (Dean Rusk)' },
        { quote: '“O importante é mudar sempre, mesmo que estejamos crescendo e ganhando o jogo”. (Masaaki Imai)' },
        { quote: '“Sempre que você vai encontrar um cliente você é a empresa”. (Barrie Hopson e Mike Scally)' },
        { quote: '“Se não puder destacar-se pelo talento, vença pelo esforço”. (Dave Weinbaum)' },
        { quote: '“Em busca do ótimo não se faz o bom”. (Segundo Mandamento da TAM)' },
        { quote: '“Se existe uma forma de fazer melhor, descubra-a”. (Thomas Edison)' },
        { quote: '“Fechar os olhos e os ouvidos para o cliente é uma loucura. É um suicídio empresarial”. (Sérgio Almeida)' },
        { quote: '“Não deixe o ruído das opiniões dos outros abafar a sua própria voz interior”. (Steve Jobs)' },
        { quote: '“Somente os que ousam errar muito podem realizar muito”. (John F. Kennedy)' },
        { quote: '“Aceite os desafios para que possa sentir o sabor da vitória”. (General George S. Patton)' },
        { quote: '“A sorte favorece a mente preparada”. (Louis Pasteur)' },
        { quote: '“Quando os momentos da verdade não são gerenciados, o serviço regride até a mediocridade”. (Karl Albrecht)' },
        { quote: '“Metas são necessárias não só para nos motivar, mas para nos manter vivos”. (Robert H. Schuller)' },
        { quote: '“Pessoas com meta têm sucesso pois sabem onde estão indo”. (Earl Nightingate)' },
        { quote: '“A pessoa comum é exigente com os outros. A superior é exigente consigo mesmo”. (Marco Aurélio, adaptado)' },
        { quote: '“Não há sucesso sem dificuldade”. (Sófocles)' },
        { quote: '“Os clientes julgam os serviços pela maneira que são tratados por aqueles com quem tem contato”. (Carl Sewell)' },
        { quote: '“Um grande prazer na vida é fazer aquilo que dizem que você não é capaz de fazer”. (Walter Gagehot)' },
        { quote: '“Toda glória advém de ousar começar”. (Eugene F. Ware)' },
        { quote: '“Todas as pequenas coisas, juntas, formam uma base de clientes fiéis e mais lucrativas”. (Bruce Hammonds)' },
        { quote: '“A pessoa que não acredita em si mesmo não acredita em mais nada”. (Roy L. Smith, adaptado)' },
        { quote: '“Grandes mentes estão prontas não apenas para explorar oportunidades, mas para criá-las”. (Cotton)' },
        { quote: '“O primeiro passo indispensável para conseguir coisas na vida é decidir o que você quer”. (Ben Stein)' },
        { quote: '“A percepção quando chega a ser julgada por outros é a realidade”. (Jack Lowenstein)' },
        { quote: '“O pior fracassado do mundo é aquele que perdeu o entusiasmo”. (H. W. Arnold)' },
        { quote: '“A maior recompensa pelo trabalho não é o que a pessoa ganha, é o que ela se torna através dele”. (John Ruskin)' },
        { quote: '“Quando as expectativas aumentam inicia-se um ciclo interminável e contínuo de melhoria”. (Steven Hronec)' },
        { quote: '“Aquele que cometeu um erro e não corrigiu está cometendo outro erro”. (Confúcio)' },
        { quote: '“A vitória sempre foi de quem nunca duvidou dela”. (Raul Follerean)' },
        { quote: '“Os satisfeitos nada mais fazem. Os insatisfeitos são os únicos propulsores do mundo”. (Walter Savage Landor)' },
        { quote: '“Todas as coisas são possíveis àqueles que creem”. (S. Marcos, 11:23)' },
        { quote: '“O problema é que a maioria das pessoas prefere um elogio que prejudique do que uma crítica que beneficie”. (Norman Vincent Peale)' },
        { quote: '“A decepção surge da disparidade entre a expectativa de uma experiência agradável e a experiência real”. (Albert Hirschman)' },
        { quote: '“Prefiro a angústia da busca do que a paz da acomodação”. (Dom Resende Costa)' },
        { quote: '“Os únicos limites das pessoas são o tamanho de suas ideias e o grau de sua dedicação”. (F. Veiga, adaptado)' },
        { quote: '“Conhecimento não é aquilo que você sabe, mas o que você faz com aquilo que sabe”. (Aldous Huxley)' },
        { quote: '“Fidelidade do cliente é a chave para lucratividade e crescimento futuro”. (Rick Tate)' },
        { quote: '“Critica o que fazes, e não faças o que criticas”. (Provérbio Árabe)' },
        { quote: '“O que merece ser feito, merece ser bem feito”. (Lord Chesterfield)' },
        { quote: '“Não encontre defeitos, encontre soluções. Qualquer um sabe queixar-se”. (Henry Ford)' },
        { quote: '“Para evitar críticas: não faça nada, não diga nada, não seja nada”. (Elbert Hubbard)' },
        { quote: '“As pessoas abominam a impessoalidade do negócio”. (Marcos Gouvêa de Souza)' },
        { quote: '“Nunca aceite o ‘não’ como resposta”. (J. F. Mitchell)' },
        { quote: '“A natureza nos deu uma língua e dois ouvidos para que ouçamos mais do que falamos”. (Diógenes Laércio)' },
        { quote: '“Se você não puder manter, não proponha nada; esta é a regra básica na satisfação do cliente”. (Sérgio Almeida)' },
        { quote: '“Feliz aquele que sabe adquirir experiência com o erro dos outros”. (Kauto)' },
        { quote: '“Querer ser de seu tempo é já estar ultrapassado”. (Eugène Ionesco)' },
        { quote: '“Planeje o seu trabalho hoje para todos os dias trabalhar o seu plano”. (Norman Vincent Peale)' },
        { quote: '“Supere a expectativa do cliente com pequenas ações frequentes e não solicitadas”. (David Freemantle)' },
        { quote: '“Sucesso é apenas sorte; pergunte para qualquer fracassado”. (Earle Wilson)' },
        { quote: '“Destino não é exterior a nós; somos nós que criamos nosso próprio destino dia após dia”. (Henry Miller)' },
        { quote: '“O homem que removeu a montanha começou carregando as pedras”. (Provérbio chinês)' },
        { quote: '“O gosto amargo da baixa qualidade dura bem mais do que a doçura do preço inferior”. (Heinz Rahnan)' },
        { quote: '“A covardia é o medo aceito; a coragem é o medo dominado”. (Lecouve)' },
        { quote: '“Todos os dias me levanto para vencer”. (Onassis)' },
        { quote: '“Meu sucesso se deve ao fato de me cercar de pessoas competentes”. (Enzo Ferrari)' },
        { quote: '“Não atrase o seu progresso com medo de fracassar”. (Nathiel Hover)' },
        { quote: '“As pessoas são a força direcional por trás do crescimento”. (Business Week)' },
        { quote: '“Quem não tem inteligência para criar tem que ter coragem para copiar”. (Sétimo Mandamento da TAM)' },
        { quote: '“Ninguém pode ferir você sem o seu consentimento”. (Eleanor Roosvelt)' },
        { quote: '“O verdadeiro risco é não fazer nada”. (Denis Waitley)' },
        { quote: '“Aquele que domina os outros é forte; aquele que domina a si mesmo é todo-poderoso”. (Lao Tsu)' },
        { quote: '“Faça o que puder, com o que tiver, onde estiver”. (Theodore Roosvelt)' },
        { quote: '“A qualidade do serviço e produto é decorrência da qualidade das pessoas”. (Claus Moller)' },
        { quote: '“Nossas dúvidas são traidoras e nos fazem perder, por medo de tentar, o que poderíamos ganhar”. (William Shakespeare)' },
        { quote: '“Os problemas são apenas oportunidades com roupas de trabalho”. (Henry John Kaiser)' },
        { quote: '“Não nos transformamos de uma hora para outra aquilo que não cooperamos para nos tornar”. (William J. Bennett)' },
        { quote: '“O que a pessoa pensa a respeito de si mesmo indica o seu destino”. (Henry David Thoreau, adaptado)' },
        { quote: '“Decidir o que não fazer é tão importante quanto decidir o que fazer. Isso é verdadeiro para companhias e também para produtos”. (Steve Jobs)' },
        { quote: '“O cliente precisa saber que nós nos importamos com ele”. (Roberto Maksoud)' },
        { quote: '“Devemos ser a mudança que queremos ver no mundo”. (Gandhi)' },
        { quote: '“Você tem que fazer as coisas que pensa não ser capaz de fazer”. (Eleanor Roosvelt)' },
        { quote: '“Em toda a iniciativa, considere aonde você poderia chegar”. (Publilius Syrus)' },
        { quote: '“Ninguém pode construir uma reputação com base naquilo que ainda vai fazer”. (Henry Ford)' },
        { quote: '“A comunicação é a principal fonte de poder pessoal”. (Fortune Magazine)' },
        { quote: '“Falhar no planejamento é um planejamento para falhar”. (Effie Jones)' },
        { quote: '“Em todas as situações, deve-se considerar o objetivo”. (Jean de La Fontaine)' },
        { quote: '“65% dos negócios de uma empresa vêm de clientes já existentes – não de novos”. (AMA)' },
        { quote: '“É o motivo que engrandece a ação; é o fazer, não o feito”. (Margaret Preston)' },
        { quote: '“Quem vive sem disciplina morre sem honra”. (Provérbio islandês)' },
        { quote: '“Mesmo se você estiver no caminho certo será atropelado se ficar sentado nele”. (Will Rogers)' },
        { quote: '“Desperdiçar o próprio tempo é uma espécie de suicídio”. (George Savile)' },
        { quote: '“A ética dá lucro para a empresa”. (Lori Tansey)' },
        { quote: '“O fanatismo consiste em redobrar esforços quando o objetivo for esquecido”. (George Santayana)' },
        { quote: '“Se você não sabe para onde vai, provavelmente terminará em algum outro lugar”. (Laurence J. Peter)' },
        { quote: '“Os atrasos deixam o cliente com os dentes rangendo”. (Fred Wiersema)' },
        { quote: '“Uma jornada de mil quilômetros começa pelo primeiro passo”. (Lao Tsu)' },
        { quote: '“Algumas derrotas são mais triunfantes do que vitórias”. (Michael de Montaigne)' },
        { quote: '“Nossa vida é o que os nossos pensamentos fazem dela”. (Marco Aurélio Antonino)' },
        { quote: '“Quem torna as coisas mais fáceis para os outros, torna as coisas mais fáceis para si”. (Ditado asiático)' },
        { quote: '“Custa 6 vezes mais conquistar um novo cliente do que manter um antigo”. (Claus Moller)' },
        { quote: '“Seja um parâmetro de qualidade. Algumas pessoas não estão acostumadas a um ambiente onde a excelência é esperada”. (Steve Jobs)' },
        { quote: '“Coragem é estar morto de medo e encilhar o cavalo mesmo assim”. (John Wayne)' },
        { quote: '“O talento sempre tem consciência de sua própria abundância e não cria objeções em dividir”. (Alexander Soljenitsyn)' },
        { quote: '“Não se pode progredir enquanto se ajustam contas”. (Dick Armey)' },
        { quote: '“O único bem coletivo é aquele que assegura o bem individual de cada cidadão”. (Charles Dickens)' },
        { quote: '“Ouça, ou sua língua vai conservar sua surdez”. (Provérbio indígena norte-americano)' },
        { quote: '“O que você dá é o que você recebe”. (Eric Berne)' },
        { quote: '“Sucesso é a soma de pequenos esforços repetidos dia sim, e no outro também”. (Robert Collier)' },
        { quote: '“É bom ter objetivo para a jornada à frente; mas, no fim, a jornada é o que importa”. (Ursula L. Le Guin)' },
        { quote: '“Jamais imponha a sua linguagem às pessoas com as quais você deseja se comunicar”. (Abbie Hoffman)' },
        { quote: '“Você tem que escutar os clientes e então agir com base no que eles disseram”. (Charles Lazarus)' },
        { quote: '“As pessoas só vêem aquilo que estão preparadas para ver”. (Ralph Waldo Emerson)' },
        { quote: '“Quem só conhece o seu lado do problema sabe pouco sobre ele”. (John Stuart Mill)' },
        { quote: '“Duas cabeças são melhores do que uma”. (John Heywood)' },
        { quote: '“Uma ideia pode virar pó ou mágica, depende do talento que esbarra nela”. (William Bernbach)' },
        { quote: '“A empresa que busca encantar o cliente é inquieta e criativa”. (Sérgio Almeida)' },
        { quote: '“A oposição traz concórdia. A discórdia vem da mais perfeita harmonia”. (Heráclito)' },
        { quote: '“Não busque todas as qualidades em uma pessoa só”. (Confúcio)' },
        { quote: '“Ter senso de humor é tão importante quanto ter talento”. (Gary Oldman)' },
        { quote: '“Todos nós somos ignorantes, só que em assuntos diferentes”. (Will Rogers)' },
        { quote: '“O plano de só uma pessoa pode ser incompleto; o de duas será melhor”. (Chuang-tsé, adaptado)' },
        { quote: '“Ninguém jamais ganha uma discussão com o cliente”. (Barrie Hopson)' },
        { quote: '“O hoje é aluno do ontem”. (Thomas Fuller)' },
        { quote: '“Jamais devemos negociar por medo, mas jamais devemos ter medo de negociar”. (John F. Kennedy)' },
        { quote: '“O tratamento deve sempre ser positivo, independente da circunstância”. (Fábio Eltz)' },
        { quote: '“Não tenha medo de tempestades, pois estarás aprendendo a manejar o barco”. (Louisa May Alcott)' },
        { quote: '“Se você pensa que educação é uma coisa cara, tente a ignorância”. (Derek Bok)' },
        { quote: '“A coisa mais difícil é a decisão de agir, o resto é apenas tenacidade”. (Amelia Earhart)' },
        { quote: '“O autodesenvolvimento é um dever maior do que o auto-sacrifício”. (Elizabeth Cady Stanton)' },
        { quote: '“Grandes descobertas e progressos envolvem a cooperação de várias mentes”. (Alexander Graham Bell)' },
        { quote: '“É preciso buscar fatias na multidão”. (Sérgio Quartiermeister)' },
        { quote: '“Caia 7 vezes. Levante-se 8”. (Provérbio japonês)' },
        { quote: '“Ninguém nasce um gênio; a pessoa se torna um”. (Simone de Beauvoir)' },
        { quote: '“Quando eu deixar de ser o que sou, eu irei me tornar o que poderia ser”. (Lao Tzu)' },
        { quote: '“Seu tempo é limitado, então não o gaste vivendo a vida de outra pessoa”. (Steve Jobs)' },
        { quote: '“A mente humana, expandida por uma ideia nova, jamais retorna à dimensão original”. (Oliver Wendell Holmes)' },
        { quote: '“A percepção é um ponto de vista individual. Portanto, não se discute”. (Sérgio Almeida)' },
        { quote: '“Você deve guardar um dragão dentro de si. Quando precisar, você deixa o dragão sair”. (Anderson Silva)' },
        { quote: '“Eu preferiria morrer de paixão do que de tédio”. (Vincent Van Gogh)' },
        { quote: '“Sonhar, afinal, é uma forma de planejamento”. (Gloria Steinem)' },
        { quote: '“O segredo do sucesso é a constância do objetivo”. (Benjamin Disraeli)' },
        { quote: '“Escreva algo que valha a pena ler, ou faça alguma coisa que valha a pena escrever”. (Benjamin Franklin)' },
        { quote: '“Saber ouvir e ter equilíbrio emocional: fundamentais no atendimento ao cliente”. (Fela Moscovici)' },
        { quote: '“É preciso ter dúvidas. Só os estúpidos têm uma confiança absoluta em si mesmos”. (Orson Welles)' },
        { quote: '“Devemos crer que somos dotados de alguma coisa, e que essa coisa, deve ser atingida a todo custo”. (Marie Curie)' },
        { quote: '“Tudo tem beleza. Mas nem todos podem ver”. (Confúcio)' },
        { quote: '“Prometa o que não irá cumprir e seus clientes formarão um mau conceito a seu respeito”. (Robert Peterson)' },
        { quote: '“Se o índice de falha é de 1 em 1 milhão, o que você responde para esse cliente?” (Pôster da IBM)' },
        { quote: '“Se você deseja que seus filhos acabem bem, gaste o dobro de tempo com eles, e metade do dinheiro”. (Abigail Van Buren)' },
        { quote: '“Use bom senso em todas as situações; não espere por regras novas, pois não virão”. (Manual da Nordstrom)' },
        { quote: '“Todo mundo tem talento, é só uma questão de se mexer até descobrir qual”. (George Lucas)' },
        { quote: '“Quanto mais nos defrontamos com tecnologia, maior nosso anseio por contatos humanos”. (John Nasbit)' },
        { quote: '“Bem começado é meio caminho andado”. (Provérbio grego)' },
        { quote: '“A mente é tudo. Você se torna aquilo que você pensa”. (Buddha)' },
        { quote: '“Uma queixa é alguém avisando que você não o satisfez. E isso é escrito em ouro”. (Donald Beaver Jr.)' },
        { quote: '“O medo de ousar, ser agressivo ou inovar fechou mais empresas do que a ousadia”. (Júlio Ribeiro)' },
        { quote: '“Minha primeira mensagem é: escute, escute e escute o pessoal que faz o trabalho”. (H. Ross Perot)' },
        { quote: '“A preguiça caminha tão devagar que a pobreza a alcança com rapidez”. (Franklin D. Roosvelt)' },
        { quote: '“Dos clientes insatisfeitos, apenas 5% efetivamente fez uma reclamação”. (Denis Walker)' },
        { quote: '“Vá na direção de seus sonhos. Viva a vida que você imaginou”. (Henry David Thoreau)' },
        { quote: '“Não existe empresa nota 10 com empregados nota 5”. (Marcos Gouvêa de Souza)' },
        { quote: '“Perder tempo é um castigo insuportável”. (Quin Guanshu)' },
        { quote: '“Serviços ao cliente não consistem em satisfação, mas sim em deslumbre”. (Chip Bell)' },
        { quote: '“Você pode destruir o seu hoje se preocupando com o amanhã”. (Janis Joplin)' },
        { quote: '“Todo cliente quer ser tratado como especial, não quer ser ‘mais um”. (Fábio Eltz)' },
        { quote: '“Começar é a parte mais importante de qualquer trabalho”. (Platão)' },
        { quote: '“Nossa meta é resolver problemas antes que os clientes saibam que eles existam”. (Ron Bern)' },
        { quote: '“Uma boa cabeça e um bom coração formam sempre uma combinação formidável”. (Nelson Mandela)' },
        { quote: '“Se você não tem item de controle, você não tem gerência”. (Kaoru Ishikawa)' },
        { quote: '“Os colaboradores evitam as queixas pois eles nunca foram instruídos a lidar com elas”. (John Tschohl)' },
        { quote: '“O maior prêmio que a vida oferece é trabalhar em algo que valha a pena”. (Theodore Roosvelt)' },
        { quote: '“Um bom porta-voz transforma leite desnatado em chantilly”. (George Lichtenberg)' },
        { quote: '“Um líder genuíno é motivador: orienta as pessoas, não as dirige; envolve, não as coage”. (J. Walters)' },
        { quote: '“A vida não é sobre ter, é sobre dar e ser”. (Kevin Kruse)' },
        { quote: '“O resultado final de um serviço é um sentimento”. (Karl Albrecht)' },
        { quote: '“O objetivo do marketing de relacionamento é a retenção de clientes”. (Terry Vavra)' },
        { quote: '“Aqueles que nada fazem estão sempre dispostos a criticar os que fazem algo”. (Paul Deschanel)' },
        { quote: '“Cliente é todo aquele impactado por seus produtos, processos e serviços”. (Juran)' },
        { quote: '“As empresas terão de adaptar-se às preferências individuais de cada consumidor ou sucumbirão”. (Raimar Richers)' },
        { quote: '“Sente-se sufocado aquele sem um objetivo de vida”. (Fiódor Dostoiévski)' },
        { quote: '“Não critique a pessoa, somente o comportamento”. (Claus Moller)' },
        { quote: '“É doce deixar a mente relaxar de vez em quando”. (Horácio)' },
        { quote: '“O presente é o único momento que temos para fazer algo”. (Ken O’Donnell)' },
        { quote: '“Todo mundo é capaz de dominar uma dor, exceto quem a sente”. (William Shakespeare)' },
        { quote: '“Desperdício é tudo aquilo que não representa valor para o cliente”. (Richard Whiteley)' },
        { quote: '“A convicção é inútil – a menos que se transforme em conduta”. (Thomas Carlyle)' },
        { quote: '“Quanto mais distante o administrador do administrado, menos eficiente a administração”. (Phillip Crosby)' },
        { quote: '“A felicidade não é algo pronto. Ela vem de suas próprias ações”. (Dalai Lama)' },
        { quote: '“Devemos seguir o exemplo dos rios: dão suas águas ao mar e nunca ficam vazios”. (Jefferson Leão de Almeida)' },
        { quote: '“Meu maior poder como consultor é ser ignorante e fazer algumas perguntas”. (Peter Drucker)' },
        { quote: '“O cliente é alguém que nos traz suas necessidades”. (L. L. Bean Inc)' },
        { quote: '“O pior erro que você pode cometer em sua vida é ficar com medo de cometer algum erro”. (Elbert Hubbard)' },
        { quote: '“Se houver uma opção melhor, os clientes mudarão de fornecedor”. (Catherine Romano)' },
        { quote: '“O alvo na vida não deve ser ultrapassar os outros, mas sim ultrapassar a nós mesmos”. (M. J. Babcock)' },
        { quote: '“Quando são cometidos lapsos nos serviços, as vendas caem”. (Terrell Harris)' },
        { quote: '“Jamais prometa mais do que pode fazer”. (Publilius Syrus)' },
        { quote: '“Se você for direto e honesto com seus clientes eles o tratarão como amigo”. (Milton Moore)' },
        { quote: '“Não arriscar nada é arriscar tudo”. (Cesare Cantú)' },
        { quote: '“Não se comprometa a fazer o que não é capaz, mas preocupe-se em manter sua promessa”. (George Washington)' },
        { quote: '“Quando você atende ao telefone, a imagem da sua empresa é percebida do outro lado da linha”. (Video Business Magazine)' },
        { quote: '“Um investimento em conhecimento sempre paga o maior juro”. (Benjamin Franklin)' },
        { quote: '“Contrate o tipo de pessoa capaz de construir relações sólidas com os clientes”. (Lunda Goldzimer)' },
        { quote: '“Não abandone suas três grandes e inabaláveis amigas: a intuição, a inocência e a fé”. (George Gurdjieff)' },
        { quote: '“Quem sabe faz a hora, não espera acontecer”. (Geraldo Vandré)' },
        { quote: '“A única coisa que sabemos sobre o futuro é que ele será diferente”. (Peter Drucker)' },
        { quote: '“Quando você perde um cliente, perde transações futuras e propaganda boca a boca”. (David Clutterbuck)' },
        { quote: '“Eu me sentia derrotado por não ter sapatos, até o dia que encontrei um homem que não tinha pés”. (Harols Abbott)' },
        { quote: '“Uma empresa que não escuta o seu cliente está fadada ao insucesso”. (Paulo Apsan)' },
        { quote: '“Se você não é notado, você não tem nada”. (Leo Burnett)' },
        { quote: '“Não são os anos de sua vida que contam. É a vida em seus anos”. (Abraham Lincoln)' },
        { quote: '“O marketing de relacionamento reduz o impacto dos esforços feitos pela concorrência”. (Don Peppers)' },
        { quote: '“É melhor ser invejado do que lastimado”. (Heródoto)' },
        { quote: '“Você pode construir o mais belo lugar do mundo, mas serão as pessoas que tornarão realidade o sonho”. (Walt Disney)' },
        { quote: '“Não existe técnica de comunicação mais relevante do que a naturalidade”. (Reinaldo Polito)' },
        { quote: '“Na vida sempre fazemos escolhas. Ainda que escolhemos não escolher”. (Carmen Miranda)' },
        { quote: '“A melhor maneira de vender é facilitando a compra”. (Sales and Marketing Magazine)' },
        { quote: '“A cortesia tem um grande poder, e não custa nada”. (Samuel Smiles)' },
        { quote: '“Você pode ficar desapontado se falhar, mas já está derrotado se não tentar”. (Beverly Sills)' },
        { quote: '“Se souber o nome do cliente, use em sua saudação”. (Texas American Bank)' },
        { quote: '“Ofereça ao cliente algo que vale a pena e ele pagará o que vale”. (Tom Peter e Nancy Austin)' },
        { quote: '“Seja hoje melhor do que ontem e, amanhã, melhor do que hoje”. (Constantino C. Vigil)' },
        { quote: '“O acordo é o último recurso dos que não têm imaginação”. (Oscar Wilde)' },
        { quote: '“Lucro é vital, mas o cliente vem antes. Sem ele não há lucro”. (Richard Whiteley)' },
        { quote: '“Sonhe grande e se atreva a falhar”. (Norman Vaughan)' },
        { quote: '“Eu sempre uso o produto dos meus clientes; não é bajulação, mas boas maneiras”. (David Ogilvy)' },
        { quote: '“Traga novas ideias e trate-as regiamente, pois uma delas pode ser o rei”. (Mark van Doren)' },
        { quote: '“Quem quer agradar a todo mundo não agrada a ninguém”. (Dito popular)' },
        { quote: '“Leve é a tarefa quando muitos dividem o trabalho”. (Samuel Johnson)' },
        { quote: '“Você seria seu próprio cliente?” (Linda Goldzimer)' },
        { quote: '“Ganhar não é tudo, mas querer ganhar é”. (Vince Lombardi)' },
        { quote: '“Aquilo que você não pode medir não pode ser aperfeiçoado”. (John Young)' },
        { quote: '“O conveniente e o correto raramente são a mesma coisa”. (Charles Brower)' },
        { quote: '“A confiabilidade do serviço é fator mais importante de todos, duas vezes acima dos demais”. (Gordon Spainhower)' },
        { quote: '“Uma pessoa que nunca cometeu um erro, nunca tentou nada de novo”. (Albert Einstein)' },
        { quote: '“Você precisa ver seus erros para poder fazer algo a respeito deles”. (Claus Moller)' },
        { quote: '“Se os ventos não vão servir, leve os remos”. (Provérbio norte-americano)' },
        { quote: '“Ninguém cativa um cliente sabendo apenas o nome e onde ele mora”. (Sérgio Quartiermeister)' },
        { quote: '“O trabalho de adivinhação torna inevitável a insatisfação”. (John Tschohol)' },
        { quote: '“Quando deixamos de contribuir, começamos a morrer”. (Eleanor Roosvelt)' },
        { quote: '“A chave do negócio é analisar cada cliente antes de servi-lo”. (Laurent Svadon)' },
        { quote: '“O problema não é o problema. O problema é a atitude com relação ao problema”. (Kelly Young)' },
        { quote: '“Verifique seus sentimentos à porta do escritório”. (Tom Peters)' },
        { quote: '“Diga ‘obrigado’ sempre que tiver uma oportunidade”. (Carl Sewell)' },
        { quote: '“Você nunca vai chegar ao seu destino se você parar e atirar pedras em cada cão que late”. (Winston Churchill)' },
        { quote: '“A confiança dos clientes é o ativo mais valioso de uma companhia de serviços”. (Leonard Berry)' },
        { quote: '“Não ergas um edifício sem fortes alicerces ou viverás com medo”. (Sabedoria Persa)' },
        { quote: '“Trate seus funcionários assim como quer que eles tratem seus melhores clientes”. (Stephen Covey)' },
        { quote: '“Somos damas e cavalheiros servindo damas e cavalheiros”. (Lema do Ritz-Carlton Hotel)' },
        { quote: '“Esforce-se para não ser um sucesso, mas sim para ser valioso”. (Albert Einstein)' },
        { quote: '“Projete um sistema que equilibre processo, produto e medidas de satisfação”. (Peter Francese)' },
        { quote: '“Ouça qualquer um que tenha uma ideia original. Encoraje-o. Deixe as pessoas continuarem suas ideias”. (William McKnight)' },
        { quote: '“Satisfaça o cliente no começo, no fim e sempre”. (Phillip Crosby)' },
        { quote: '“Eu não falhei no teste. Eu só encontrei 100 maneiras de fazer errado”. (Benjamin Franklin)' },
        { quote: '“Quer segurança em um emprego? Faça um cliente feliz”. (Júlio Lobos)' },
        { quote: '“O essencial é invisível aos olhos”. (Antoine de Saint-Exupéry)' },
        { quote: '“Conheça seus clientes como sua família, satisfaça-os e você terá sucesso”. (Richard Whiteley)' },
        { quote: '“Um cliente que reclama é um consultor. Aponta o que melhorar e não cobra nada por isso”. (Sérgio Almeida)' },
        { quote: '“Nunca é tarde demais para ser o que você poderia ter sido”. (George Eliot)' },
        { quote: '“Não existe melhor publicidade do que um cliente satisfeito”. (Jay Curry e Ludovic Stora)' },
        { quote: '“Gerenciar não é mais a direção da coisa, mas o aperfeiçoamento das pessoas”. (Alvin Toffler)' },
        { quote: '“A pessoa no comando não pode apenas pregar. Ela precisa liderar com exemplos”. (Carl Sewell)' },
        { quote: '“A marca é um símbolo que identifica uma promessa na cabeça do cliente”. (Larry Light)' },
        { quote: '“Não há saber mais ou saber menos: há saberes diferentes”. (Paulo Freire)' },
        { quote: '“O papel do gerente é de orientar, energizar e estimular”. (Jack Welck)' },
        { quote: '“Se você quiser se levantar, levante outra pessoa”. (Booker T. Washington)' },
        { quote: '“Você pode tosquiar o carneiro por muitos anos, mas poderá esfolá-lo somente uma vez”. (John Sewell)' },
        { quote: '“Quanto maior a dificuldade maior é o mérito de superá-la”. (H. W. Beecher)' },
        { quote: '“Cuidar o lado emocional do cliente é mais importante do que consertar um equipamento”. (Bill Bleuel)' },
        { quote: '“O cliente compra uma promessa e são obrigados a confiar que a empresa ira cumpri-la”. (Leonard Berry)' },
        { quote: '“A questão não é quem vai me deixar; mas sim, quem vai me impedir”. (Ayn Rand)' },
        { quote: '“Certifique-se de que suas palavras e seus atos estão em harmonia”. (Claus Moller)' },
        { quote: '“As pessoas estão atentas a você. A qualidade está no seu coração”. (Steven Leonard Jr.)' },
        { quote: '“Nossa paciência conquistará mais do que a nossa força”. (Edmund Burke)' },
        { quote: '“Se os clientes não estão reclamando você está perdendo a oportunidade de ser melhor”. (Karl Albrecht)' },
        { quote: '“Você pode mudar sem crescer, mas não pode crescer sem mudar”. (Larry Wilson)' },
        { quote: '“Agradeça com um sorriso a presença do cliente”. (Texas American Bank)' },
        { quote: '“Você não crescerá a não ser que tente algo além daquilo que já domina”. (Ronald Osborn)' },
        { quote: '“Faça a voz do cliente ecoar em toda a empresa”. (Richard Whiteley)' },
        { quote: '“Tudo o que você sempre quis está do outro lado do seu medo”. (George Addair)' },
        { quote: '“Nada contribui tanto para clarear a mente do que um objetivo claro”. (Marry W. Shelley)' },
        { quote: '“Um único pensamento pode revolucionar sua vida”. (Norman Vincent Peale)' },
        { quote: '“Todo o marketing da sua empresa pode ser anulado por um único empregado grosseiro”. (John Tschohl)' },
        { quote: '“Quando compreende-se o que o cliente deseja, torna-se mais fácil atendê-lo”. (Fábio Eltz)' },
        { quote: '“Só serão felizes aqueles que procurarem e encontrarem um meio de servir”. (Albert Schweitzer)' },
        { quote: '“A percepção que o cliente tem em relação ao seu produto é o que determina sua satisfação”. (Linda Goldzimer)' },
        { quote: '“O mais corajoso dos atos ainda é pensar com a própria cabeça”. (Coco Chanel)' },
        { quote: '“A coisa mais importante para o cliente é: você fez aquilo que prometeu?” (Carl Sewell)' },
        { quote: '“Nada que valha a pena acontece a alguém exceto o resultado do trabalho árduo”. (Booker T. Washington)' },
        { quote: '“A forma mais barata de manter clientes satisfeitos é servi-los bem desde o começo”. (Fortune Magazine)' },
        { quote: '“A melhor forma de ter clientes para sempre é oferecer a eles um negócio irrecusável”. (Don Peppers)' },
        { quote: '“Tenho aprendido ao longo dos anos que, quando a mente está pronta, isso diminui o medo”. (Rosa Parks)' },
        { quote: '“O cliente é o chefe”. (Lema da Bio-Lab)' },
        { quote: '“Mestre não é quem sempre ensina, mas quem de repente aprende”. (João Guimarães Rosa)' },
        { quote: '“Se não agrega valor, pare; se faz sentido para o cliente, prossiga”. (Bob Harbage)' },
        { quote: '“Os clientes sempre reconhecem quando alguém saiu do seu caminho para ajudá-los”. (Leonard Berry)' },
        { quote: '“Espíritos grandiosos sempre encontraram oposição violenta de mentes medíocres”. (Albert Einstein)' },
        { quote: '“A busca da qualidade é um estado de espírito”. (Cesare Romiti)' },
        { quote: '“O que é realmente necessário em empresa que presta serviço são pessoas que gostem de pessoas”. (Frank Petro)' },
        { quote: '“É importante aprender a não se aborrecer com opiniões diferentes das suas”. (Bertrand Russell)' },
        { quote: '“O melhor vendedor do mundo é um cliente encantado”. (Sérgio Almeida)' },
        { quote: '“Ter problemas na vida é inevitável. Ser derrotado por eles é opcional”. (Roger Crowford)' },
        { quote: '“Limitar o foco ao cliente provoca uma espécie de cegueira para inovações”. (Paulo Apsan)' },
        { quote: '“A prestação de bons serviços nunca é acidental”. (Jaclyn Jeffrey)' },
        { quote: '“Você nunca pode atravessar o oceano até que você tenha coragem de perder de vista a costa”. (Cristóvão Colombo)' },
        { quote: '“O que pode sair errado? Essa é a pergunta a se fazer ao projetar os seus sistemas”. (Carl Sewell)' },
        { quote: '“Toma conta do teu negócio ou ele tomará conta de ti”. (Benjamin Franklin)' },
        { quote: '“A satisfação do cliente é uma relação entre o que ele viu e o que ele esperava ver”. (Sérgio Almeida)' },
        { quote: '“Perde tudo quem perde o momento certo”. (Provérbio espanhol)' },
        { quote: '“Combata a mediocridade – em si e nos outros”. (Claus Moller)' },
        { quote: '“Lembre-se que não conseguir o que você quer é algumas vezes um lance de sorte”. (Dalai Lama)' },
        { quote: '“Uma atitude vitoriosa é meio caminho andado para o sucesso”. (Arthur Riedel)' },
        { quote: '“Agregar valor é resolver os problemas do cliente”. (James Belasco)' },
        { quote: '“Fazer rápido obriga-o a fazer certo logo na primeira vez”. (John Young)' },
        { quote: '“Devemos preferir as queixas aos cumprimentos”. (Donald Beaver Jr.)' },
        { quote: '“Todos os sorrisos do mundo não irão ajudá-lo se o produto ou serviço não for o que o cliente deseja”. (Carl Sewell)' },
        { quote: '“Um serviço excelente é uma estratégia de lucro”. (Leonard Berry)' },
        { quote: '“Você pode tudo se tiver entusiasmo”. (Henry Ford)' },
        { quote: '“Não sei aonde vou, mas já estou no caminho”. (Carl Sandburg)' },
        { quote: '“Conte a verdade – ou não conte nada. Ninguém gosta de gente mentirosa”. (Fortune Magazine)' },
        { quote: '“O insucesso é uma oportunidade para recomeçar com mais inteligência”. (Henry Ford)' },
    ]
}